export const FETCH_ARTISTS_BEGIN   = 'FETCH_ARTISTS_BEGIN';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAILURE = 'FETCH_ARTISTS_FAILURE';
export const FETCH_ARTIST_BEGIN  = 'FETCH_ARTIST_BEGIN';
export const FETCH_ARTIST_SUCCESS ='FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_FAILURE ='FETCH_ARTIST_FAILURE';

export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_FAILURE='SEARCH_FAILURE'
